name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Test
      run: |
        go test -v ./...
        go test -v -race ./...
 
    - name: Make dist
      run: |
        if [ ! -d dist ]; then
          mkdir dist
        fi

    - name: Build
      run: go build -v -o dist/govanityurls .

    - name: upload-binary
      uses: actions/upload-artifact@v2
      with: 
        path: dist

    - name: upload-event
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.event_path }}
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
  bump_version:
    needs: build
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: clly/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
  
